spring:
  cache:
    type: redis
    redis:
      cache-null-values: true
      time-to-live: 40000
  data:
    redis:
      host: localhost
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'false'
server:
  error:
    include-message: always
